[package]
name = "rs-matter-macros"
version = "0.1.0"
edition = "2021"
authors = [
        "Kedar Sovani <kedars@gmail.com>",
        "Ivan Markov",
        "Project CHIP Authors",
]
description = "Native Rust implementation of the Matter (Smart-Home) ecosystem - Proc-macros"
repository = "https://github.com/project-chip/matter-rs"
readme = "README.md"
keywords = ["matter", "smart", "smart-home", "IoT", "ESP32"]
categories = ["embedded", "network-programming"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.48", features = ["extra-traits", "parsing"] }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "3.0.0"

rs-matter-data-model = { path = "../rs-matter-data-model", features=["idl"] }
rs-matter-macros-impl = { path = "../rs-matter-macros-impl" }
