name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "50 6 * * *"
  workflow_dispatch:

env:
  RUST_TOOLCHAIN: stable
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crypto-backend: ['rustcrypto', 'mbedtls', 'openssl']
        features: ['', 'alloc', 'os']

    steps:
      - name: Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy, rust-src

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --no-deps --no-default-features --features ${{matrix.crypto-backend}},${{matrix.features}} -- -Dwarnings

      - name: Build
        run: cargo build --no-default-features --features ${{matrix.crypto-backend}},${{matrix.features}}

      - name: Benchmark
        run: cargo bench --no-default-features --features ${{matrix.crypto-backend}},${{matrix.features}}

      - name: Test
        if: matrix.features == 'os'
        run: cargo test --no-default-features --features ${{matrix.crypto-backend}},${{matrix.features}}
