name: PublishMacrosDryRun

on: workflow_dispatch

env:
  RUST_TOOLCHAIN: stable

jobs:
  publish_macros_dry_run:
    name: PublishMacrosDryRun
    runs-on: ubuntu-latest
    steps:
      - name: Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy, rust-src

      - name: Checkout
        uses: actions/checkout@v3

      - name: PublishDryRun-Macros
        run: cargo publish -p rs-matter-macros --dry-run
