name: PublishMacros

on: workflow_dispatch

env:
  RUST_TOOLCHAIN: stable

jobs:
  publish_macros:
    name: PublishMacros
    runs-on: ubuntu-latest
    steps:
      - name: Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy, rust-src

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish-Macros
        run: cargo publish -p rs-matter-macros
